networks:
  dev:
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - backend
      - frontend
    networks:
      - dev
  db:
    image: postgres:16
    container_name: maqas_postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: popa2007
      POSTGRES_DB: maqas_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    networks:
      - dev
  frontend:
    build:
      context: ./frontend
    networks:
      - dev

volumes:
  postgres_data:
