
user  root;

worker_processes  1;

events {
}


http {
    server {
        listen       80;
        
        server_name  72.56.250.175;
        location / {
            proxy_pass http://frontend:80/;
        }
        location /api/ {
            proxy_pass http://backend:8000/;
        }

    }

}
