"""blacklist

Revision ID: 0de83fa6d748
Revises: 3fbea2b7d03f
Create Date: 2026-05-08 15:17:58.162418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0de83fa6d748'
down_revision: Union[str, Sequence[str], None] = '3fbea2b7d03f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('black_list',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('blocker_id', sa.UUID(), nullable=False),
    sa.Column('blocking_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['blocker_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['blocking_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blocker_id', 'blocking_id', name='unique_black_list')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('black_list')
    # ### end Alembic commands ###
