"""likes

Revision ID: 3b75d02eaf28
Revises: 649d5a09a57f
Create Date: 2026-06-16 16:23:04.916022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b75d02eaf28'
down_revision: Union[str, Sequence[str], None] = '649d5a09a57f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'posts',
    sa.Column('likes_count', sa.Integer(), server_default='0', nullable=False)
	)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'likes_count')
    # ### end Alembic commands ###
